#!/bin/bash
echo hello
touch abc cde efg hij
cat >> abc
ls -ltr
date
print'hello how are you'
print" bhubaneswar is the capital of Odishs"
print"Puri is famous for Lord Jagganath"
echo "hello"\n " are you man"
echo "hello"\e "i am in cuttack"