#!/bin/bash


echo " Delhi is the capital of India"
echo ' Kolkata remained capital of India for 1100 years'
echo shifted from Kolkata to Delhi in 1911
echo " comming from us"
echo " Ram \n shyam \n gyan"

